### ISSUE TITLE
Em Space (U+2003) treated as non-breaking space

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#123]
It appears that the line break algorithm treats Em Space (U+2003) as a non-breaking space. Note that in the screenshot below, the first three lines really ought to extend to the next word, but because the next word is followed by an Em Space, it gets moved to the start of the next line.

![image](https://user-images.githubusercontent.com/915182/85531167-bb003c00-b638-11ea-943d-55c8ab127f15.png)

Because our language uses Em Space as the equivalent of English comma (pause in a sentence), we use it all over the place, and lines like this add up, probably adding a page or two by the end (and making the right column excessively jagged). I wonder whether there might be a solution? Ideally, an Em Space would be parsed like a normal space for line breaking, so that if it comes at the end of the line, it drops out, making no impact on the layout.

**Comment by davidg-sil** [comment]
You seem to be correct, Em-space is indeed treated as a non-breaking character in XeTeX.
If you're feeling brave, the following, added to the .tex file, will redefine it to be an active character, and define that as a slightly flexible space, of width 1em. Note that it may not have the same length as an in-font em-space. (At least, in 14pt Gentium: 1em measures 14pt, an "M" is 11.29pt wide, and em-space is 10.73, whereas in 14pt Ariel, emspace is 14pt wide and an M is 11.66pt.)

\catcode"2003=13
\def^^^^2003{\hskip 1em plus 2pt minus 2pt}

There is a possibility that doing this will break something, but hopefully not!  If you want it to be rigidly one em, no matter the circumstances, make it {\hskip 1em}.

**Comment by davidg-sil** [comment]
Mark, would this be a useful extra snippet to add?

**Comment by markpenny** [comment]
Just wondering about what other things might come up like this - which would mean adding more to the already overcrowded UI. If there's a simple-enough tweak (as above) that can be added to the user's ptxprint-mods.tex file and it works, then that's probably good enough. However if the snippet would benefit dozens of others in a region or around the world, (OR have ability to serve other similar needs at the same time) then it might be a worthy candidate to add to the UI.

**Comment by viverechristus** [comment]
I created a file named ptxprint-mods.tex, put only the suggested code snippet (as below) into the file, and moved it to the PrintDraft folder. In ptxprint I then selected Apply Customized Settings (in ptxprint-mods.tex) and clicked Print. The progress bar goes half way and freezes, and the program becomes unresponsive.

```
\catcode"2003=13
\def^^^^2003{\hskip 1em plus 2pt minus 2pt}
```

Here you can see the file in its location (is this the right location?):

![image](https://user-images.githubusercontent.com/915182/85664629-a8dbd780-b6e4-11ea-9034-bf3ae42fbfc6.png)

If I go to the Advanced tab and, having ticked "Apply Customized Settings (in ptxprint-mods.tex)", I then click "Edit", ptxprint is not finding the file. It gives me the following message in the Viewer tab:

![image](https://user-images.githubusercontent.com/915182/85664870-f48e8100-b6e4-11ea-906f-1a48fbd0cccc.png)

If you can give me some further guidance about where to put the code snippet, I'll try it out. I don't need this built into the program as long as I can get the code read locally! Thanks.

**Comment by markpenny** [comment]
Fixed - there was a bug with the path to the .tex file. What you have done above is the right thing. It should now work in 0.8.6 or later.

**Comment by viverechristus** [comment]
Confirmed - it works. But where is the file "ptxprint-mods.tex" saving? PTXprint is still not finding the file in the [Project]/PrintDraft folder. I have to edit the file from inside the program by clicking on "Edit" and then adding the code snippet. When I save, it has no impact on the file in the PrintDraft folder, so it seems to be buried somewhere, unlike the other customization files.

**Comment by viverechristus** [comment]
I'm afraid this fix (designed to make em-space a flexible breaking character) no longer works in 1.3.

I have the following code (and nothing else) in ptxprint-mods.tex:

```
\catcode"2003=13
\def^^^^2003{\hskip 1em plus 2pt minus 2pt}
```

Here's the relevant portion from the Log:

```
(c:/My Paratext 8 Projects/JraKhmr/PrintDraft/ptxprint-Matthew-Standard-MAT_GLO
JraKhmr.notepages)
(using pictures from list "ptxprint-Matthew-Standard-MAT_GLOJraKhmr.piclist")
\langund=\language98
(../shared/ptxprint/Matthew-Standard/ptxprint-mods.tex
! Missing control sequence inserted.
<inserted text> 
                \inaccessible 
<to be read again> 
                   ^
l.4 \def^
         ^^^2003{\hskip 1em plus 2pt minus 2pt} 
```

**Comment by davidg-sil** [comment]
Hi, the macros now define it as the non-flexible (rigid) version. Therefore the \catcode line shouldn't be needed.  Or the whole file if you're happy with the rigid version.
I don't understand how you're getting the error, and wonder if the catcode line has something else odd in it, or if there is some kind of error in how / when the file is included.

**Comment by viverechristus** [comment]
Should I do anything at this point, or wait on the development team? (I can't presently get an output for other reasons, issue #277, but once that's resolved I can see what's happening with em-space if I don't call this code.)

**Comment by markpenny** [comment]
@viverechristus Could you confirm whether you still have an issue here, or has this one been resolved?

**Comment by viverechristus** [comment]
Just had my first successful output in a while -- and this seems to be fixed. Thanks!
