### ISSUE TITLE
In 0.9.1 I'm still not able to get the end of book decoration to show

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#174]
I may be missing something here, but I can't get the decoration to show. And I also noticed the file I chose is not listed in the Config file (like I think it should be).

**Comment by mhosken** [comment]
This is not necessarily going to be fixed with 1.0 Please stop raising new issues on this. I will just close them.

**Comment by davidc86** [comment]
I’m confused.
You have the feature in the app, and it doesn’t work AT ALL, and you say to stop worrying about it?
I’m not badgering about it not crossing double columns or any fancy thing like that. I’m saying why have the feature in the app unless it at least does something?
It should be blocking v1 if it doesn’t work at all. Either gray it out completely and we can’t access it, marking it as a “future feature” or hide it completely, because right now, it behaves like a major bug.
In fact in v0.9.2 if I try to activate that feature, it kills the PRINT process. (No action at all when Print is pressed.)
If I turn off that feature, PRINT runs just fine.
To me that is a blocking bug!

**Comment by davidc86** [comment]
Okay, I just got 0.9.3, and verified a slight improvement: if I select the “decoration.pdf” file buried in the default border-art folder in PTXprint’s Program Files folder, I can get the PRINT button to actually format the PDF, but is still does NOT place any decoration at the end of any book. (Again why have the feature if it doesn’t work?)

But if I select any file outside of that buried default folder, the PRINT button fails immediately. (Doesn’t even turn green.)

Sorry to be a bother, but do you really want anything in the app UI that is non-functional, or worse kills the whole purpose of the app? To me, this issue should be addressed before v1. It doesn’t have to be perfect or anything, but a feature should never kill the Print process, and if selected, it should actually do something.

David

From: David Coward
Sent: Wednesday, 12 August, 2020 8:13 AM
To: sillsdev/ptx2pdf <reply@reply.github.com>; sillsdev/ptx2pdf <ptx2pdf@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [sillsdev/ptx2pdf] In 0.9.1 I'm still not able to get the end of book decoration to show (#174)

I’m confused.
You have the feature in the app, and it doesn’t work AT ALL, and you say to stop worrying about it?
I’m not badgering about it not crossing double columns or any fancy thing like that. I’m saying why have the feature in the app unless it at least does something?
It should be blocking v1 if it doesn’t work at all. Either gray it out completely and we can’t access it, marking it as a “future feature” or hide it completely, because right now, it behaves like a major bug.
In fact in v0.9.2 if I try to activate that feature, it kills the PRINT process. (No action at all when Print is pressed.)
If I turn off that feature, PRINT runs just fine.
To me that is a blocking bug!

**Comment by markpenny** [comment]
Hi again David, I'm still perplexed as to why this isn't working right for you. I can't get it to fail yet. I have also looked into the .cfg file and can see:
```
[fancy]
enableborders = True
endofbook = True
endofbookpdf = ${pdfassets}/border-art/decoration.pdf
pageborder = True
pageborderpdf = ${pdfassets}/border-art/A5 page border.pdf
sectionheader = True
sectionheaderpdf = ${pdfassets}/border-art/A5 section head border.pdf
versedecorator = True
versedecoratorpdf = ${pdfassets}/border-art/Verse number star.pdf
versenumsize = 10.500

```
This tells me that it *should* be remembering the settings and using them. Can you confirm that you are selecting **PDF files** for these additional decorations?
![image](https://user-images.githubusercontent.com/12962708/90088001-2087c380-dd72-11ea-8994-d76dc9b591dd.png)
And at the end of the book I see the decoration.pdf:
![image](https://user-images.githubusercontent.com/12962708/90088053-3ac1a180-dd72-11ea-9958-8cf4f549449a.png)

The only other thing that I can suggest is that the font hasn't been defined here and might be tripping it up, but that should at least give you a UI error rather than do nothing.
![image](https://user-images.githubusercontent.com/12962708/90088189-807e6a00-dd72-11ea-84a6-523763bbf536.png)

**Comment by mhosken** [comment]
Whenever one has the situation of "Print fails with no failure dialog" then the next step in debugging is to run ptxprint.exe -l and try again and then submit the contents of ptxprint.log that is generated in the current working directory from which you ran the ptxprint command. Generally there is a python stack trace in there that we can use to find out why ptxprint is so upset.

**Comment by jeffheath-sil** [comment]
Just FYI - with 0.9.3 beta, I am also not seeing the decoration at the end of the book. In PTXPrint:
![image](https://user-images.githubusercontent.com/14953913/90114149-3bded880-dd4a-11ea-842d-942df3feeca4.png)

The .tex file seems to declare it reasonably:
```
\newbox\decorationbox
\setbox\decorationbox=\hbox{\XeTeXpdffile "C:/Program Files/PTXprint/ptxprint/PDFassets/border-art/decoration.pdf"\relax}
\def\z{\par\nobreak\vskip 16pt\centerline{\copy\decorationbox}}
```
And the \z seems to be added OK in the Final SFM:
```
\v 19 Kaaka pa ku aɗoŋ oko giimi ku ballee paracco ku kiɗaati, kuu leeɗiy gu deeɗo jobookeetaw. Kuu batisiyɗiy ma semeetee Mella Baaba o ku Runti o ku Ruuhanti.
\v 20 Kuu garkiyɗiy maa gu jobbiɗiy beneyyiŋgeetaw paracco maa na beneyyitoŋ. Naa pa aaye aɗe goŋŋa ma kuŋ meeni paracco namma ya dessiti dunuuniti. »


\z
```
Although in my XeTeX processing, the \z has a line break after it, and the decoration appears. The Final SFM ends with the \z without a line break. Not a chance that a line without a line break at the end in the SFM doesn't get processed? But it sounds like the feature is working for Mark? Hmmm...

OK, some more info. I see from Mark's screen shots above that he has verse number stars and section heading boxes working as well. When I check those options, I still don't get them. They still seem to be using the "default file names, not the names/paths that I selected:

```
    \global\setbox\sectionheadbox=\hbox{\XeTeXpdffile "sectHeadDecorator.pdf"\relax}%
...
\setbox\versestarbox=\hbox{\XeTeXpdffile "verseNumDecorator.pdf"\relax}
```
That's probably a separate issue, but worth noting...

And BTW, I started with a brand new .cfg file a day or two ago.

**Comment by davidc86** [comment]
Ah, right, well there was a difference between your config file and mine (which I started from scratch at 0.9.1). Yours had path and filenames in it. Mine did not. But now running 0.9.3 I am seeing this: 

[fancy]
enableborders = True
endofbook = True
endofbookpdf = ${workingdir}/EndofBookDesign.pdf
pageborder = False
sectionheader = False
versedecorator = False
versenumsize = 11.000

So the path and filename are now showing up! Woohoo. But unfortunately, the decoration is still not being put into the PDF document. But at least now the PDF document formats and exports to a file successfully, which is a huge improvement.

Where do you want me to look to help you track down this odd behavior?

**Comment by davidc86** [comment]
Using v1.0 I still am not getting the end of chapter decorations. 
In the output SFM (like Jeff said) I see an empty \z line.
Do I need to specify somewhere what to do with that \z line? (In a styelsheet?) Because, like Jeff, I'm still not seeing this.

**Comment by davidc86** [comment]
On a side note: Even when the config file has the spec:
**endofbookpdf = ${workingdir}/EndofBookDesign.pdf** 

Whenever I click on the Select button next to that specification, PTXprint **_never_** opens the file picker dialog at the stored location of my previous file, rather it automatically falls back to the embedded (and obscure to normal users) location of: 
**C:\Program Files\PTXprint\ptxprint\PDFassets\border-art\**

Could we please get PTXprint to recognize the {workingdir} path and use it as the default location when we click the Select buttons? (Normal users, on a Windows machine, should _never_ need to look inside a "Program Files" folder.)  
I don't know if this odd inconsistency is related to this current issue, but it is worth throwing out there while this feature is being reviewed.

**Comment by mhosken** [comment]
Side issue moved to a new issue #188 given this issue, as original stated, is resolved and is liable to close on that basis.

**Comment by davidc86** [comment]
Here we are in v1.1.9 and I still can't get End of Book decorations working. Here is my screen shot: 

![image](https://user-images.githubusercontent.com/65363206/94326760-4d83e480-ff74-11ea-8130-31528bee069a.png)

The path is to the Project's PrintDraft folder, rather than to Program Files. It is also in a different place than the folder where all the illustrations are kept. 

Since I've never gotten the decoration to print, I'm in the dark as to what might be blocking it.

**Comment by jeffheath-sil** [comment]
Yeah, I’m a little bit baffled as well, since obviously (from screen shots above) MarkP has gotten them to work.

**Comment by mhosken** [comment]
Closing this issue. All discussion to be moved to #155
