### ISSUE TITLE
Xref callers problem

### ISSUE THREAD

**Issue by RossWebb** [sillsdev/ptx2pdf#339]
Using PTXprint 1.5

No matter how I set the xref options I cannot get the caller '-' to not appear in the text. I thought that the '-' between the \x and \xo was to turn the caller off, and I don't have the overide specific setting checked.

![image](https://user-images.githubusercontent.com/21695272/104115336-5604fd00-5362-11eb-9250-446fac1740e8.png)

Also the xref referer can get disconnected from the set of references. See the yellow highlight in the screenshot.

Settings used:

![image](https://user-images.githubusercontent.com/21695272/104115355-b6943a00-5362-11eb-8006-622cb8a8fdf2.png)

**Comment by mhosken** [comment]
Thanks. Yes there is a bug in the macros regarding the hyphen caller, which I have now fixed, so you should see this problem resolved in a future version.

As to your second issue of breaking between the reference and the text. We don't insert a full non breaking space after the reference. Instead we insert a 'we strongly suggest you don't break here' break instead. We found that if we make it impossible for TeX to break after a reference, then worse things happen in how things look for justified note blocks or other line breaks.

Just getting TeXnical for a moment, should you want to go there, you can override how terrible it is for TeX to break a line at that point by editing your ptxprint-mods.tex and inserting something like:
```
\badspacepenalty=100
```
which is the current default. You can increase that penalty to make it harder for TeX to break there or you can reduce it to make it easier for TeX to break there. But do notice that this break penalty is also used for things like final words in poetry, etc. As a measure of scale, 10000 will prohibit a break and the cost is in badness squared so a cost of 400 is about twice as bad as 100 and likewise 1600 is twice as bad as 400, etc.

**Comment by RossWebb** [comment]
Hi Martin(?)

Thanks for your instructions on breaks in the cross-ref area and the function of \badspacepenalty. Very tricky!

I just downloaded 1.5.1 which has that the xref problem has been fixed in the release notes.
However the problem still appears to remain for me... (check the attachement)

I tried it with both the "overide" function turned on but the caller field left blank, and with the 'overide' function off. The results were the same. With 'overide' on and a caller like * put in the caller field, the correct caller does appear in the text.

Am I doing something wrong. I'll include a screenshot of my setup on the xref page..

Thanks for your help,
Ross

[Ross Webb - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=ursr7)	[ursr7]

On January 11, 2021 at 3:29 GMT, mhosken <notifications@github.com> wrote:

Thanks. Yes there is a bug in the macros regarding the hyphen caller, which I have now fixed, so you should see this problem resolved in a future version.

As to your second issue of breaking between the reference and the text. We don't insert a full non breaking space after the reference. Instead we insert a 'we strongly suggest you don't break here' break instead. We found that if we make it impossible for TeX to break after a reference, then worse things happen in how things look for justified note blocks or other line breaks.

Just getting TeXnical for a moment, should you want to go there, you can override how terrible it is for TeX to break a line at that point by editing your ptxprint-mods.tex and inserting something like:
\badspacepenalty=100
which is the current default. You can increase that penalty to make it harder for TeX to break there or you can reduce it to make it easier for TeX to break there. But do notice that this break penalty is also used for things like final words in poetry, etc. As a measure of scale, 10000 will prohibit a break and the cost is in badness squared so a cost of 400 is about twice as bad as 100 and likewise 1600 is twice as bad as 400, etc.

**Comment by RossWebb** [comment]
Just to confirm that the caller problem with xrefs is still happening. This time  I am attempting to print a project that has a + in the \x + \xo code and am trying to remove it (otherwise the caller appears as a superscript number next to the verse number - rather confusing. I would like nothing in the text, not even the - that is appearing at the moment.

![image](https://user-images.githubusercontent.com/21695272/104528759-3c163380-565c-11eb-8191-6ece19ab3136.png)

**Comment by markpenny** [comment]
@mhosken I wonder if this might be related to "Blend Cross-references in with footnotes" - which looks like it is enabled in the screenshot above.

**Comment by mhosken** [comment]
I can't replicate your problem here, any longer, so I'll need an archive from you. Please send an archive (advanced tab) (see issue #280 for details). TIA.

**Comment by RossWebb** [comment]
[Tuma_Fnl-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/5839439/Tuma_Fnl-DefaultPTXprintArchive.zip)
I just tried this with a different project. The xrefs are coded with a hard * between the \x and \xo. If I don't override the xref settings, I get the * as the caller with no callee in the xref area.
If I tick Override and untick Callers and Callees, then I get the - as the caller.
If I tick Override and tick Callers (and have nothing in the adjacent field) then I get no Caller or Callee (!!!SUCCESS!!!)
If I tick Override and untick Callers but tick Callee, I get neither (I'd expect a Callee, but not a Caller)
If I tick OVerride and untick both, I get neither (as expected).
If I tick Override, tick Caller (and add a caller to the field) and tick Callee, I get both (as expected)

This works the same way for the project for which I raised the ticket that has \x - \xo for xrefs
I can now remove the - from the Caller and Callee by having Override ticked and Callee with nothing in the adjacent field.

Sorry, a bit convuluted.

**Comment by markpenny** [comment]
We think this is fixed in 1.5.5. Please check, and ensure that you're editing the right hand side if you're expecting changes to the \\xr output (and the Left hand side for the \\fr).

**Comment by RossWebb** [comment]
Yes I am, Mark.
Did you see what I wrote to Martin(?) yesterday?
Ross

[Ross Webb - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=v8zyn)	[v8zyn]

On January 21, 2021 at 4:11 GMT, Mark Penny <notifications@github.com> wrote:

We think this is fixed in 1.5.5. Please check, and ensure that you're editing the right hand side if you're expecting changes to the \xr output (and the Left hand side for the \fr).

**Comment by markpenny** [comment]
Yes, and MH made some changes, and I've also made the interface a bit more logical so that setting combinations that don't make sense can't be selected. 1.5.6 will have these changes - please let us know how it goes; and whether we've managed to solve the problem(s) you experienced in earlier versions.

**Comment by RossWebb** [comment]
Seems my problems are solved, Mark.
However, I wonder whether you've experienced this...
I am using a change to put in a new page before each chapter. That works (apart from an error message that doesn't seem to stop play), however, the 2nd page of each chapter doesn't get a page number. It seems that it's not that the program doesn't just not print the number (in the footer) for every 2nd page because if there is only one page of a particular chapter, then the next chapter gets a page number - i.e. it's not an odd/even thing.

Ross

[Ross Webb - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=vg02g)	[vg02g]

On January 21, 2021 at 9:36 GMT, Mark Penny <notifications@github.com> wrote:

Yes, and MH made some changes, and I've also made the interface a bit more logical so that setting combinations that don't make sense can't be selected. 1.5.6 will have these changes - please let us know how it goes; and whether we've managed to solve the problem(s) you experienced in earlier versions.

**Comment by markpenny** [comment]
@RossWebb  - Could you please test to see if you're getting this issue in 1.5.8 which can be [downloaded from here](https://software.sil.org/downloads/r/ptxprint/SetupPTXprint(1.5.8).exe). If so, close the issue. If not, then use "Create Archive..." on the advanced tab to send us a project that we can replicate the issue with. Thanks

**Comment by RossWebb** [comment]
Hi Mark,

I downloaded 1.5.8 and it doesn't work well, sorry to say.
I am try to print a Bible story project which printed in 1.5.7 but gave an error with the changes.txt being used.
Now I get a catestrophic error whether 'changes' are selected or not.I tried creating an archive, but got this error and a zero byte archive zip file.

Please send this error message to ptxprint_support@sil.org

PTXprint Version 1.5.8

Traceback (most recent call last):
File "ptxprint\gtkview.py", line 1957, in onCreateZipArchiveClicked
File "ptxprint\view.py", line 1039, in createArchive
File "ptxprint\view.py", line 1054, in _archiveAdd
File "ptxprint\view.py", line 972, in _getArchiveFiles
File "ntpath.py", line 229, in basename
File "ntpath.py", line 198, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType

<class 'TypeError'>: expected str, bytes or os.PathLike object, not NoneType

[Ross Webb](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=vne9b)	[vne9b]

[Check out Bible Translation in Vanuatu](https://facebook.com/vanuatuBible)

On January 28, 2021 at 22:52 GMT, Mark Penny <notifications@github.com> wrote:

[@RossWebb](https://github.com/RossWebb) - Could you please test to see if you're getting this issue in 1.5.8 which can be [downloaded from here](https://software.sil.org/downloads/r/ptxprint/SetupPTXprint(1.5.8).exe). If so, close the issue. If not, then use "Create Archive..." on the advanced tab to send us a project that we can replicate the issue with. Thanks

**Comment by markpenny** [comment]
@RossWebb Sorry about that! There were some last minute changes late yesterday which were related to making PTXprint independent of Paratext, and I suspect we've inadvertently introduced some path-related bugs. We'll see what we can do to fix it today.
