### ISSUE TITLE
Picture copyright labels have gotten messed up

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#776]
In v2.2.40 I can't get the copyright label to use a "white"/"light" background. Instead I get this: 

![image](https://user-images.githubusercontent.com/65363206/202849345-932a0520-cb78-489e-bba2-f26de9d0690a.png)

I can get transparent, but that is not useful very often (unless a slight bit of extra spacing was automatically added underneath the pictures to give some room for the labels).

Dark does the same as Light. So it looks like a glitch to me.

**Comment by davidc86** [comment]
Sorry, not fixed, or maybe "broken again in another way" would be more accurate.

The background for the © David C Cook option on pictures is no longer working correctly. The background options are changing the _font attributes_, not the _background_. The background is remaining transparent. But for most publications we need black letters on a white background. (We have 4 publications we are hoping to get into the printers soon, so this is kind of a blocking bug for us.)

WIth "bl,0,None" we get this:
![image](https://user-images.githubusercontent.com/65363206/229258036-977080d0-a74f-47c2-82ad-42964d2901ab.png)

With "bl,0,Light" we get this:
![image](https://user-images.githubusercontent.com/65363206/229258117-b6969aad-126c-4e61-b5e9-8254bed57dc9.png)

With "bl,0,Dark" we get this:
![image](https://user-images.githubusercontent.com/65363206/229258176-338e5bd7-8a42-4bfc-9e2c-2d01421e59ac.png)

**Comment by davidg-sil** [comment]
The  credit ('background box') styles ought to be working in the latest release (2.3.4). 

The credit text and its background box are formatted according to a *limited subset* of style items from the styles settings, under e.g. "Dark|x-credit" (which I find under Peripheral materials, for some reason).
The usable controls are:
* Font
* Font Size Factor
* Bold / Italic / Small caps.
* Text color (beside the font)
* Background Color ('sidebar settings')
 
Other controls are ignored.
![image](https://user-images.githubusercontent.com/58848232/230013208-6d330dea-a035-443e-b004-cebf47c0062d.png)

The user interface allows you to select 'Light', 'Dark' and 'None' as options from the dropdown list. If these three aren't sufficient for your use, you may create your own styles in the normal way, naming it according to the same scheme as the others, (e.g. making a style for 'Mystyle|x-credit') and then manually enter them instead in the text box that the user interface gives you.
![image](https://user-images.githubusercontent.com/58848232/230011912-21146f7c-f90d-40a2-872c-9af6327ab11c.png)

**Comment by davidc86** [comment]
Wow! This is amazing capabilities. I would never have found this or even known to look for it in styles. Nice to see these features represented in there. 
From this detailed dialog, I'm still not quite sure what controls the actual position of the text box itself. The picture copyright dialog specs even has vertical orientation along the sides of the pictures. So what Style handles those details. (I ask because of the issues talked about in #780 and #853 (sorry for making 2--found the other one after I'd made the new one).

**Comment by davidg-sil** [comment]
The text of the credit is put into a tight box, which is then 'grown' on all sides by the FigCreditPadding global setting.
The position of the box is set to top/bottom/centre, left/right/centre by the 2 letter code, per picture (e.g., in the example above, cl = centre left). 
The number following it is rotation (0,90,180,270).  In terms of the `\fig` attributes (or piclist entry), the three values in the above example turn into x-creditpos="cl" x-creditrot="90" x-creditbox="Mystyle"

The TeX code tries to obey instructions and doesn't presuppose what is actually a sane value, and thus will do what you say if you give it a position of "cc" (shown here with a rotation of 180).
![image](https://user-images.githubusercontent.com/58848232/230098271-799e8742-eb68-47d8-9c68-2b9cd7523d69.png).

The TeX code **should** handle all details stuff beyond that itself, and obviously makes some mistakes given #780  and the positioning of the box when inverted:
![image](https://user-images.githubusercontent.com/58848232/230098722-5e922eee-90f0-415e-b6ae-7d931e2c39ad.png)

In the interests of full disclosure, due to the interaction of the PDF codes which rotate the text and TeX (which does not have trigonometric functions), the positioning code becomes entirely confused if you give rotations other than those above, but the rotation will still be applied if it gets to the piclist: (here shown with manually-written piclist, x-creditrot="30" x-creditpos="bl")
![image](https://user-images.githubusercontent.com/58848232/230100960-b87dce09-e7bc-4036-bbff-301caec73b5e.png)
