### ISSUE TITLE
UI does not seem to save fractional cutout positions.

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#808]
Cutout positions can be fractions of a line, to allow for more precise positioning of the image within the cutout. The UI allows setting fractional values but it seems to turn the fraction into an integer when you try do actually do this.

Turning the value into a (positive) integer is correct for paragraph offsets, but incorrect for cutouts.

**Comment by markpenny** [comment]
@mhosken This is what needs to be fixed:

![image](https://user-images.githubusercontent.com/12962708/234481111-00616121-284c-462f-a7bb-90dbf101a3df.png)

@davidg-sil At present the UI only allows multiples of 0.5 as the step value. Should this be changes to allow more refined values such as 3.7 with a step of 0.1?

**Comment by davidg-sil** [comment]
I would have thought so, yes.
Well... maybe not: I don't know it's possible in the world of glade, but the fractional values are *only* valid when it's counting lines for cutouts, not when counting paragraphs. The tool tip says that, so I guess it's not possible, in which case maybe 0.5 and allowing people to set other values is a good compromise.

**Comment by davidg-sil** [comment]
While talking UI issues on that page, 'Before verse' strikes me as a bit confusing, even with the tool-tip. Would 'Immediate' work?

**Comment by mhosken** [comment]
tentative fix committed

**Comment by markpenny** [comment]
The fix hasn't changed anything (yet). The .piclist file still has a rounded number "cl3" instead of what the UI shows "cl2.5":

`RUT 1.11 rūtun gir sēriyaḍun barobar nayomi son inval|src="co00956b.tif" size="col" pgpos="cl3" ref="1:15" scale="0.4"`

**Comment by markpenny** [comment]
This is still broken (as of 2.3.22):
![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/5e61caf0-af0c-4c7d-a906-63a39930809a)

and the UI doesn't allow + / - to be clicked when it is a Paragraph:
![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/e4946002-ce16-4671-a75f-330f2bfa8f98)

**Comment by davidg-sil** [comment]
Still broken. I've been doing some digging. Bug looks to be connected to the field being prefixed `s_`

**Comment by davidg-sil** [comment]
Still broken. (pre-2.6.5)
To update / reiterate, there are 2 problems:
1. **PYTHON CODE**:  The decimal portion of the cutout position should get to the piclist, not just the integer.
2. **UI element:** As this is intended for fine positioning of the figure in the cutout, with 1.5= "2 lines, raised half a line" and 1.49 = "1 line, but lowered (almost) half a line",  the UI field should allow for smaller increments (0.1 or even 0.01 lines)

**Comment by markpenny** [comment]
Fixed for 2.6.8
![Image](https://github.com/user-attachments/assets/d98e1562-dcde-40a5-9663-0194b4976713)
